### ISSUE TITLE
Tries to run hello task which one is not defined

### ISSUE THREAD

**Issue by jurkust** [opsxcq/tasker#2]
Tries to run `hello` task which one is not defined.
This is config which one is applied through environment:
```yaml
schedules:
  - every: 1 minutes
    task: back-cron
tasks:
  docker:
    - name: back-cron
      image: my-img
      script:
        - echo Running the back-cron
logging:
  level:
    ROOT: WARN
    org.springframework.web: WARN
```
Fails with this error:
```
tasker_1  | 2018-04-10 11:19:32.244  WARN 5 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerSetup': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Defined task not found hello aborting application boot
tasker_1  | 2018-04-10 11:19:32.260 ERROR 5 --- [           main] o.s.boot.SpringApplication               : Application startup failed
tasker_1  |
tasker_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerSetup': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Defined task not found hello aborting application boot
...
```
And by default it shouldn't output so much debugging info :)
